name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */24 * * *" # Esegui ogni 24 ore
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif
          
      - name: Push changes
        uses: EndBug/add-and-commit@v7
        with:
          branch: main
          message: 'Generate Snake'
          add: "dist"
